#+title: Readme

* Getting Started
While switching to =nixos= this repository helps providing a clean and modular =NixOS= setup, keeping the following in mind:


Use =configuration.nix= for system-wide settings (e.g., services, networking, boot) and =home.nix= for user-level packages, dotfiles, and settings.

** TL:DR
- ~configuration.nix~ for system-level configuration;
- ~home.nix~ using ~home-manager~ for user configs.


* 🚀 Quickstart

1. Clone this repo inside your =NixOS= install:

#+begin_src shell
nix-shell -p git
git clone https://github.com/ac-commits/nixos-dotfiles .
#+end_src

2. Edit =configuration.nix= or a [[./default.configuration.nix][default configuration file]] :
#+begin_src bash
sudo cp nixos-dotfiles/nix/configuration.nix /etc/nixos/configuration.nix
#+end_src

3. Reboot, remove install media,  and :boom: you're in:

#+begin_src shell
sudo nixos-rebuild switch -v
#+end_src

* 🏠 Home Manager

Already baked in via =configuration.nix=:

#+begin_src nix
imports = [
  ./hardware-configuration.nix
   <home-manager/nixos>
];

home-manager.users.yourusername = import ./home.nix;
#+end_src

"Home is where your =~/.config= is." /See what I did there?/
[[./default.home.nix][default home file]]
---


* Virtualisation
#+begin_quote
Broadcoms Complexity is the worst enemy of security, and our VM's are
getting more complex all the time
#+end_quote
*AKA:* /Data and Goliath/ *BRUCE SCHEiER*

Due to the incompatibilty of =vmware workstation pro= with =kernel 6.15 >== there are 2 options:
1. switching to =virt-manager= # which I did?
2. Use pinned =pkgs.packages= for =vmware-workstation= to a specific lower kernel.


* 🔁 Updating

For full =system + user= config:

#+begin_src shell
sudo nixos-rebuild switch
#+end_src

Just tweaking user-level settings?

#+begin_src shell
home-manager switch
#+end_src

Test :test: first:

#+begin_src shell
nixos-rebuild build or dry-run
#+end_src


* 🧹 Keep it Clean

- One system to rule them all
- One config to version them
- One command to switch them all
- And in =/etc/nixos/= bind them

---

* 📚 Learn More

- [[https://nixos.org/manual/nixos/stable/][NixOS Manual]]
- [[https://github.com/nix-community/home-manager][Home Manager Docs]]
- [[https://nixos.wiki][NixOS Wiki]]

---

* 🪪 License

MIT or your preferred license, but feel free to copy the vibe too.


* Contributions
Feel free to fork and submit pull requests. Suggestions and improvements are welcome!
